
CREATE TABLE claims_transactions(
 Id VARCHAR(100)
,CLAIMID VARCHAR(100)
,CHARGEID VARCHAR(100)
,PATIENTID VARCHAR(100)
,TYPE VARCHAR(100)
,AMOUNT FLOAT
,METHOD VARCHAR(100)
,FROMDATE TIMESTAMP
,TODATE TIMESTAMP
,PLACEOFSERVICE VARCHAR(100)
,PROCEDURECODE VARCHAR(50)
,MODIFIER1 VARCHAR(20)
,MODIFIER2 VARCHAR(20)
,DIAGNOSISREF1 VARCHAR(10)
,DIAGNOSISREF2 VARCHAR(10)
,DIAGNOSISREF3 VARCHAR(10)
,DIAGNOSISREF4 VARCHAR(10)


,UNITS VARCHAR(100)
,DEPARTMENTID VARCHAR(100)
,NOTES VARCHAR(100)
,UNITAMOUNT FLOAT
,TRANSFEROUTID VARCHAR(100)
,TRANSFERTYPE VARCHAR(100)
,PAYMENTS FLOAT
,ADJUSTMENTS FLOAT
,TRANSFERS FLOAT
,OUTSTADNING FLOAT
,APPOINTMENTID VARCHAR(100)
,LINENOTE VARCHAR(100)
,PATIENTINSURANCEID VARCHAR(100)

,FEESCHEDULEID VARCHAR(50)

,PROVIDERID VARCHAR(100)
,SUPERVISINGPROVIDERID VARCHAR(100)
);
