

CREATE TABLE claims_transactions(
 Id VARCHAR(100)
,CLAIMID(100)
,CHARGEID VARCHAR(100)
,PATIENTID VARCHAR(100)
,TYPE VARCHAR(100)
,AMOUNT FLOAT
,METHOD VARCHAR(100)
,FROMDATE TIMESTAMP
,TODATE TIMESTAMP
,PLACEOFSERVICE VARCHAR(100)
,PROCEDURECODE VARCHAR(50)
,MODIFIER1 VARCHAR(20)
,MODIFIER2 VARCHAR(20)
,DIAGNOSISREF1 VARCHAR(10)
,DIAGNOSISREF2 VARCHAR(10)
,DIAGNOSISREF3 VARCHAR(10)
,DIAGNOSISREF4 VARCHAR(10)


,UNITS VARCHAR(100)
,DEPARTMENTID VARCHAR(100)
,NOTES VARCHAR(100)
,UNITAMOUNT FLOAT
,TRANSFEROUTID VAR(100)
,TRANSFERTYPE VAR(100)
,PAYMENTS FLOAT
,ADJUSTMENTS FLOAT
,TRANSFERS FLOAT
,OUTSTADNING FLOAT
,APPOINTMENTID VAR(100)
,LINENOTE VAR(100)
,PATIENTINSURANCEID VAR(100)

,FEESCHEDULEID VARCHAR(50)

,PROVIDERID VARCHAR(100)
,SUPERVISINGPROVIDERID VARCHAR(100)
);
